# Generated by Django 3.0.6 on 2020-10-04 22:08

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'OrdersItem', 'verbose_name_plural': 'OrderItems'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='price',
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_mode',
            field=models.CharField(choices=[('a', 'Card'), ('b', 'Cash')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='transactions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_source', to='api.Orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='trans_id',
            field=models.CharField(default=api.models.increment_trans_no, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='description not available', max_length=300),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
