# Generated by Django 3.0.6 on 2020-08-25 22:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='trans_id',
            field=models.CharField(default=api.models.increment_trans_no, max_length=20),
        ),
    ]
