# Generated by Django 3.0.6 on 2020-08-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200825_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'OrdersItem', 'verbose_name_plural': 'OrderItems'},
        ),
        migrations.AddField(
            model_name='orderitems',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
