# Generated by Django 3.0.6 on 2020-09-23 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200828_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_mode',
            field=models.CharField(choices=[('a', 'Card'), ('b', 'Cash')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='transactions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_source', to='api.Orders'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='description not available', max_length=300),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
