# Generated by Django 3.0.6 on 2020-09-11 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orderitems_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='transactions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_source', to='api.Orders'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='description not available', max_length=300),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
