# Generated by Django 3.0.6 on 2020-09-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200911_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_mode',
            field=models.CharField(choices=[('a', 'Card'), ('b', 'Cash')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='description not available', max_length=300, null=True),
        ),
    ]
